# Generated by Django 5.1 on 2024-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_todoitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
