# Generated by Django 5.1 on 2024-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_todoitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
